ViewComponents/TrendingViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace CodebitsBlog.ViewComponents
{
    [ViewComponent(Name = "Trending")]
    public class TrendingViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Views/Shared/Components/Culture/Default.cshtml
@model CodebitsBlog.ViewModels.PostGridViewModel

<section id="posts" class="posts">
    <div class="container" data-aos="fade-up">
        <div class="section-header d-flex justify-content-between align-items-center mb-5">
            <h2>Culture</h2>
            <div><a href="category.html" class="more">See All Lifestyle</a></div>
        </div>
        <div class="row g-5">
            <div class="col-lg-4">
                <div class="post-entry-1 lg">
                    <a href="single-post.html"><img src="@Url.Content(Model.rootPath + Model.EntryPost.CoverImageUrl)" alt="" class="img-fluid"></a>
                    <div class="post-meta"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>@Model.EntryPost.PostDate</span></div>
                    <h2><a href="single-post.html">@Model.EntryPost.Title</a></h2>


                    <div class="d-flex align-items-center author">
                        <div class="photo"><img src="@Url.Content(Model.rootPath + @Model.EntryPost.PostAuthorImageUrl)" alt="" class="img-fluid"></div>
                        <div class="name">
                            <h3 class="m-0 p-0">@Model.EntryPost.PostAuthor</h3>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-8">
                <div class="row g-5">

                    @{
                        foreach (var row in Model.GridPosts)
                        {
                            <div class="col-lg-4 border-start custom-border">
                                @foreach (var post in row.Value)
                                {
                                    <div class="post-entry-1">
                                        <a href="single-post.html"><img src="@Url.Content(Model.rootPath + @post.CoverImageUrl)" alt="" class="img-fluid"></a>
                                        <div class="post-meta"><span class="date">@post.Category</span> <span class="mx-1">&bullet;</span> <span>@post.PostDate</span></div>
                                        <h2><a href="single-post.html">@post.Title</a></h2>
                                    </div>
                                }
                            </div>
                        }
                    }

                    <!-- Trending Section -->
                    <div class="col-lg-4">

                        <div class="trending">
                            <h3>Trending</h3>
                            @await Component.InvokeAsync("Trending")
                        </div>

                    </div> <!-- End Trending Section -->
                </div>
            </div>

        </div> <!-- End .row -->
    </div>
</section>